[tool.poetry]
name = "aiostomp-py"
version = "0.1.0"
description = ""
authors = ["pengyj <p15281826276@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
